{% set name = "geovista-slam" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cef887445d5371c0932770d6f6500a06bffc7a7a8d55c42eb0d504301ce7bd0b

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61
    - setuptools-scm >=7
  run:
    - python >=3.9
    - geovista >=0.2
    - iris >=3.2

test:
  imports:
    - slam 

about:
  home: https://github.com/bjlittle/geovista-slam
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: GeoVista utility to convert CF UGRID Local Area Model quad-cell meshes into structured rectilinear or curvilinear grids 
  description: GeoVista utility to convert CF UGRID Local Area Model quad-cell meshes into structured rectilinear or curvilinear grids 
  
extra:
  recipe-maintainers:
    - bjlittle
